### ISSUE TITLE
非常有价值的工作！请问下后续会考虑把数据公开吗，想尝试一下？

### ISSUE THREAD

**Issue by sri-hk** [InteractiveNLP-Team/RoleLLM-public#1]

**Comment by wxl1999** [comment]
+1

**Comment by liujiaheng** [comment]
Yes, the data will be released.

**Comment by sri-hk** [comment]
> Yes, the data will be released.

中国人不骗中国人！

**Comment by liujiaheng** [comment]
We have released the data. Thanks for following our paper.

**Comment by sri-hk** [comment]
> We have released the data. Thanks for following our paper.

好人一生平安！

**Comment by Minami-su** [comment]
@sri-hk 
你好，我有相似的工作，代码，数据集，模型全部都开源https://github.com/Minami-su/character_AI_open
