### ISSUE TITLE
有人用GLM复现出50.5的分数了吗？

### ISSUE THREAD

**Issue by Turing-Sheep** [InteractiveNLP-Team/RoleLLM-public#15]

**Comment by Turing-Sheep** [comment]
我微调出来的GLM只有在do_sample=False，num_beams=5的情况下才能复现出50.5分，但是按照论文里的设置并未复现出，只有46分

**Comment by eeet9** [comment]
> 我微调出来的GLM只有在do_sample=False，num_beams=5的情况下才能复现出50.5分，但是按照论文里的设置并未复现出，只有46分

求问，复现代码的时候是直接使用roll bench里的数据微调吗，还是需要对数据格式进行改动

**Comment by Turing-Sheep** [comment]
用GLM2的预训练模型按照论文中的推理设置，也无法复现出39.8分，只有28分，不知道哪里写错了，希望作者能公开一下代码。

**Comment by Turing-Sheep** [comment]
> > 我微调出来的GLM只有在do_sample=False，num_beams=5的情况下才能复现出50.5分，但是按照论文里的设置并未复现出，只有46分
> 
> 求问，复现代码的时候是直接使用roll bench里的数据微调吗，还是需要对数据格式进行改动

把数据集里的数据拼成对应的角色描述提示，然后训练的。我是这样做的，如果有问题的话，可以加你qq讨论一下。

**Comment by txy77** [comment]
> > > 我微调出来的GLM只有在do_sample=False，num_beams=5的情况下才能复现出50.5分，但是按照论文里的设置并未复现出，只有46分
> > 
> > 
> > 求问，复现代码的时候是直接使用roll bench里的数据微调吗，还是需要对数据格式进行改动
> 
> 把数据集里的数据拼成对应的角色描述提示，然后训练的。我是这样做的，如果有问题的话，可以加你qq讨论一下。

能否加一下联系方式询问一下微调的相关问题呢？

**Comment by Turing-Sheep** [comment]
> > > > 我微调出来的GLM只有在do_sample=False，num_beams=5的情况下才能复现出50.5分，但是按照论文里的设置并未复现出，只有46分
> > > 
> > > 
> > > 求问，复现代码的时候是直接使用roll bench里的数据微调吗，还是需要对数据格式进行改动
> > 
> > 
> > 把数据集里的数据拼成对应的角色描述提示，然后训练的。我是这样做的，如果有问题的话，可以加你qq讨论一下。
> 
> 能否加一下联系方式询问一下微调的相关问题呢？

qq:3993695362
