### ISSUE TITLE
Two questions about the data

### ISSUE THREAD

**Issue by qby10** [InteractiveNLP-Team/RoleLLM-public#4]
Great job! There are two questions here.
1. The response styles of RoleBench-general-zh and RoleBench-specific-zh are completely different. The latter does not seem to imitate the speaking tone of the target character. 
2. All data are single-turn, which may lead to multi-turn dialogue are not effective.

**Comment by ZenMoore** [comment]
Thank you for your feedback.
Indeed, the speaking style of RoleBench-specific is less distinct than that of RoleBench-general. We've highlighted this point in footnote 8 of our paper.
You're right. Generating multi-turn dialogues can be time-consuming and costly. We suggest readers utilize the [Baize](https://arxiv.org/pdf/2304.01196.pdf) or [Camel](https://www.camel-ai.org/) techniques for this purpose.
